[package]
name = "nnls"
version = "0.4.0"
authors = ["Nil Goyette <nil.goyette@imeka.ca>"]
edition = "2021"

description = "Non-Negative Least Squares (nnls)"
repository = "https://github.com/imeka/nnls"
readme = "README.md"
keywords = ["math", "nnls", "solver"]
categories = ["mathematics", "science", "algorithms"]
license = "BSD-2-Clause"

[dev-dependencies]
criterion = "0.8"

[dependencies]
approx = "0.5"
ndarray = { version = "0.17", features = ["approx"] }
ndarray-stats = "0.7"

[[bench]]
name = "nnls"
harness = false
